const employees = [
  {
    id: 1,
    email: "employee1@company.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Design Landing Page",
        taskDescription: "Create a responsive landing page UI",
        taskDate: "2026-02-01",
        taskAssignTo: "Employee 1",
        taskCategory: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Fix Navbar Bug",
        taskDescription: "Resolve navbar alignment issue",
        taskDate: "2026-02-03",
        taskAssignTo: "Employee 1",
        taskCategory: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Update Icons",
        taskDescription: "Replace old icons with SVG icons",
        taskDate: "2026-01-28",
        taskAssignTo: "Employee 1",
        taskCategory: "UI",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 2,
    email: "employee2@company.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Create API Endpoints",
        taskDescription: "Develop REST APIs for tasks module",
        taskDate: "2026-02-02",
        taskAssignTo: "Employee 2",
        taskCategory: "Backend",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Database Optimization",
        taskDescription: "Optimize employee table queries",
        taskDate: "2026-01-30",
        taskAssignTo: "Employee 2",
        taskCategory: "Database",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "JWT Auth Setup",
        taskDescription: "Implement JWT authentication",
        taskDate: "2026-02-04",
        taskAssignTo: "Employee 2",
        taskCategory: "Security",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    email: "employee3@company.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Write Unit Tests",
        taskDescription: "Write tests for employee module",
        taskDate: "2026-02-01",
        taskAssignTo: "Employee 3",
        taskCategory: "Testing",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Bug Fixing",
        taskDescription: "Fix reported frontend bugs",
        taskDate: "2026-01-29",
        taskAssignTo: "Employee 3",
        taskCategory: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Deploy to Staging",
        taskDescription: "Deploy latest build to staging server",
        taskDate: "2026-02-05",
        taskAssignTo: "Employee 3",
        taskCategory: "Deployment",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    email: "employee4@company.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Create Wireframes",
        taskDescription: "Design wireframes for dashboard",
        taskDate: "2026-02-01",
        taskAssignTo: "Employee 4",
        taskCategory: "UX",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "User Feedback Review",
        taskDescription: "Analyze user feedback reports",
        taskDate: "2026-01-27",
        taskAssignTo: "Employee 4",
        taskCategory: "Research",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Color Palette Update",
        taskDescription: "Update project color theme",
        taskDate: "2026-02-03",
        taskAssignTo: "Employee 4",
        taskCategory: "Design",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    email: "employee5@company.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Prepare Documentation",
        taskDescription: "Write system documentation",
        taskDate: "2026-02-02",
        taskAssignTo: "Employee 5",
        taskCategory: "Documentation",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Client Meeting",
        taskDescription: "Attend client requirement meeting",
        taskDate: "2026-01-28",
        taskAssignTo: "Employee 5",
        taskCategory: "Meeting",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Report Submission",
        taskDescription: "Submit weekly progress report",
        taskDate: "2026-02-04",
        taskAssignTo: "Employee 5",
        taskCategory: "Reporting",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employess", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employess"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
